### registration
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email":"alessio@gmail.com",
    "username":"user123",
    "password":"1234"
}

### userlist
GET  http://localhost:3000/api/users
Content-Type: application/json

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"alessio@gmail.com",
    "password":"1234"
}

### logout
DELETE  http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: 


### user Update
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: 31e52028e54f

{
    "newUsername":"banana"
}

### auth List
GET http://localhost:3000/api/auths
Content-Type: application/json


### user Delete
DELETE  http://localhost:3000/api/user/delete
Content-Type: application/json  
Authorization:

{
    "primayKey":""
}

### create Ad
POST http://localhost:3000/api/ads/create
Content-Type: application/json
Authorization: 69886dcc4960c

{
    "title":"sgabello",
    "status":true,
    "photo":"UrlPhoto",
    "description":"sgabello bello",
    "category":"mobili",
    "price": "un nichelino",
    "address":"via silvio berlusconi",
    "phone":"329853472",
    "referenceKeyUser":"f9451c69ed856",
    "referenceKeyUserPurchased":""
}

### update Ad
POST http://localhost:3000/api/ads/update
Content-Type: application/json
Authorization: 69886dcc4960c

{
 "title":,
    "status":,
    "photo":,
    "description":,
    "category":,
    "price":,
    "address":,
    "phone":,
    "referenceKeyUser":,
    "referenceKeyUserPurchased":   
}

### delete Ad
DELETE http://localhost:3000/api/ads/delete 
Content-Type: application/json
Authorization: 69886dcc4960c

{
    "referenceKeyAds":"354479f6a1a13"
}

### ad List
GET http://localhost:3000/api/ads
Content-Type: application/json

### update Ad Status
PUT http://localhost:3000/api/ads/status
Content-Type: application/json
Authorization: 

{
    "referenceKeyAds":,
    "status":
}

### create Review
POST http://localhost:3000/api/reviews/create
Content-Type: application/json
Authorization: 6667858e8b779

{
    "title":"ok",
    "description":"molto bello",
    "rating":"4",
    "referenceKeyAd":"a2be01fce4775",
    "referenceKeyUser":"283039e3b7f28"
}

### update Review
POST http://localhost:3000/api/reviews/update
Content-Type: application/json
Authorization: 

{
  "title":"ok",
    "description":"molto bello",
    "rating":"4",
    "referenceKeyAd":"a2be01fce4775",
    "referenceKeyUser":"283039e3b7f28"   
}

### delete Review
DELETE http://localhost:3000/api/reviews/delete
Content-Type: application/json
Authorization: 

{
    "referenceKeyReview":"",
    "referenceKeyUser":"" 
}

### review List
GET  http://localhost:3000/api/reviews
Content-Type: application/json

### add Favorite
POST http://localhost:3000/api/favorites/create
Content-Type: application/json
Authorization: 

{
    "referenceKeyAd":"",
    "referenceKeyUser":""
}

### delete Favorite
DELETE http://localhost:3000/api/favorites/delete
Content-Type: application/json
Authorization: 

{
   "referenceKeyAd":"",
    "referenceKeyUser":"" 
}

### favourite List
Get http://localhost:3000/api/favorites
Content-Type: application/json
