### registration
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email":"alessio@gmail.com",
    "username":"user123",
    "password":"1234"
}

### userlist
GET  http://localhost:3000/api/users
Content-Type: application/json

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"alessio@gmail.com",
    "password":"1234"
}

### logout
DELETE  http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: 734e0aa7a6a3f


### user Update
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: 31e52028e54f

{
    "newUsername":"banana"
}

### auth List
GET http://localhost:3000/api/api/users
Content-Type: application/json


### user Delete
DELETE  http://localhost:3000/api/user/delete
Content-Type: application/json  
Authorization: 31e52028e54f

{
    "primayKey":""
}

### create Ad
POST http://localhost:3000/api/ads/create
Content-Type: application/json
Authorization: 31e52028e54f

{
    "title":"sgabello",
    "status":true,
    "photo":"UrlPhoto",
    "description":"sgabello bello",
    "category":"mobili",
    "price": "un nichelino",
    "address":"via silvio berlusconi",
    "phone":"329853472",
    "referenceKeyUser":"f9451c69ed856",
    "referenceKeyUserPurchased":""
}

### update Ad
POST http://localhost:3000/api/ads/update
Content-Type: application/json

{
 "title":,
    "status":,
    "photo":,
    "description":,
    "category":,
    "price":,
    "address":,
    "phone":,
    "referenceKeyUser":,
    "referenceKeyUserPurchased":,
    "token":   
}

### delete Ad
DELETE http://localhost:3000/api/ads/delete 
Content-Type: application/json
Authorization: 31e52028e54f

{
    "referenceKeyAds":"",
}

### ad List
GET http://localhost:3000/api/ads
Content-Type: application/json

### update Ad Status
PUT http://localhost:3000/api/ads/status
Content-Type: application/json
Authorization: 

{
    "referenceKeyAds":,
    "status":,
}

### create Review
POST http://localhost:3000/api/reviews/create
Content-Type: application/json
Authorization: 

{
    "title":"",
    "description":,
    "rating":,
    "referenceKeyAd":,
    "referenceKeyUser":
}

### update Review
